from:
  relationshipName: Add item to cart
  slug: product-catalog
  mergeColumns: false
to:
  slug: add-item-to-cart
  mergeColumns: false
cardinality: 1:many
mapping:
  - fromColumn: SKU
    toColumn: SKU
